### ISSUE TITLE
Initial setup of organization cm12-amami

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#1]
Hi @hahnjo, @Micha-Btz ,

I have initially setup the organization and done the 1st build.
I'll be away over the long weekend (until Tuesday), afterwards, I'll work on the manifest to include the majority of the local manifest into the main manifest.

Regards - M.

**Comment by Micha-Btz** [comment]
we need just a cool organisation icon :-)

**Comment by MSe1969** [comment]
If you have an idea for a cool icon - go for it (only be careful with copyrighted stuff and brand logos)

**Comment by MSe1969** [comment]
Hi @hahnjo @Micha-Btz - besides a cool logo, should we also create a github project web page? It is in fact not that difficult (but of course requires initially a huge amount of "try & error & get familiar" time)
Not the highest priority, but would be something nice...

**Comment by Micha-Btz** [comment]
webpage why not but we should find a logo first.

**Comment by MSe1969** [comment]
What about this as a logo?
https://www.iconfinder.com/icons/27626/9000_hal_light_red_space_icon

**Comment by Micha-Btz** [comment]
for me ok @hahnjo ?

**Comment by MSe1969** [comment]
Have set it :)

**Comment by MSe1969** [comment]
As our new org. is now working and has got a logo, I am closing this issue.
With regards to a github page, we may want to get back to that later, if we feel the need for it...
