### ISSUE TITLE
Further security hardening

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#10]
We should implement the following security hardening measures in our ROM:

1. **SQLite "secure delete" (Upstream backport)**
https://android-review.googlesource.com/q/topic:%22secure_delete%22+(status:open%20OR%20status:merged)

2. **Patch against ultrasonic cross-device tracking**
For info, see http://ubeacsec.org, the patch is here: https://github.com/ubeacsec/AOSP-Patch
The implementation however should be done not as a permission, but as a flag in the developer options, where users can choose to **disable** the patch

3. **Restrict network monitoring in 'untrusted' user apps**
Inspired by this article https://www.kuketz-blog.de/android-erlaubt-apps-vollen-zugriff-auf-die-netzwerkaktivitaet/, which also has lead to a corresponding implementation Copperhead OS (https://copperhead.co/android/docs/technical_overview, chapter "Enhanced SELinux policies", last section), we also should adapt the SELinux policy (approach: copy untrusted_app.te to netmonitor.te, remove the mentioned entry in untrusted_app.te, create an entry in mac_permissions.xml for those apps, where this access should still be allowed (proposal: "Privacy Friendly Netmonitor" (SecuSo)), which we should then bundle as prebuilt) and add the netmonitor context to the seapp_contexts file.

**Comment by Micha-Btz** [comment]
I'm always for security enhancements so 1 and 2 are absolutely ok. The solution for 2 as permission I don't like too. 
3 is a different story to me. This is more a design problem by android itself then a issue and can easily solved with a firewall. The firewall has the positive effect that the user have done this on this own. If we create a sepolicy then there will be permission errors possible because we can not test all apps. Also I don't like to add an app which I don't want and don't want to use. Since it will be a system app I even can't remove it on the standard way. 
@hahnjo what do you think?

**Comment by hahnjo** [comment]
I think we shouldn't do any of this: In my opinion we are just maintaining a working ROM, not adding new features. Every piece you add has the possibility to break something. In this case, especially 3) but all the other points as well.

**Comment by MSe1969** [comment]
topic 1: is a standard feature available in SQLite - Google has switched it on in Oreo, and I don't see any reason, why we shouln't use it. My test build runs fine with it, no issues so far.

topic 2: we can't really implement it, so best is to drop and forget about it:
The patch requires some MM coding in frameworks/av - to get it even near a workable state, some android 6 commits have to be cherry-picked, which implements a new "sub-class". As specifically frameworks/av has a "permanent subscription" in every ASB, this would really open the potential of further security weaknesses and other compatibility issues.

topic 3: well, both of you don't want to explore that path, so we have already a decision to drop it.

**Comment by MSe1969** [comment]
Topic 1 implemented, topics 2 and 3 withdrawn - issue closed
