### ISSUE TITLE
Tag android-5.1.1_r38

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#12]
When CyanogenMod stopped working on the cm-12.1 branch end of 2016, the manifest still tracked AOSP tag android-5.1.1_r37, whilst meanwhile tag android-5.1.1_r38 was published.
We should therefore analyse, whether commits are missing or not properly backported.
In order to do so, I have synch'ed AOSP tag android-5.1.1_r38 (excluding kernel, device, chromium_org trees) and created a delta-list between r37 and r38 to check the commits.

**Comment by MSe1969** [comment]
UPDATE:
Analyzed and found three repos with differences:
external/aac - pushed two missing commits to cm-12.1-test
frameworks/av - pushed one missing commit to cm-12.1-test

packages/services/Telephony/
The below commit is missing, but the code differs, so cannot be picked in a trivial way:
fe5f4ffef DO NOT MERGE Use E PhoneAccount for MT ECM Call Brad Ebinger Thu Mar 24 17:48:59 2016 -0700
>> further analysis required

**Comment by MSe1969** [comment]
This is the "Telephony" commit mentioned in my previous post
https://android.googlesource.com/platform/packages/services/Telephony/+/fe5f4ffef74924112ed9d9b248e1ab025323c40c

Maybe you would like to have a look? I tend to simply skip it and leave it alone. Seems that here, CyanogenMod decided to use a slightly different code, maybe from caf... - as far as I see it, this anyhow seems to be CDMA related and we don't have anybody using our ROM in a CDMA network anyhow...

**Comment by MSe1969** [comment]
@hahnjo @Micha-Btz - I have added file **LP_r37-r38_Changes.txt** to the discussion repo.
Maybe you would like to also check on your side, whether I may have overlooked a commit, which isn't yet applied, besides the four mentioned by me?

**Comment by Micha-Btz** [comment]
Skip the telephony patch is right. Did you push all needed patches for this?

**Comment by MSe1969** [comment]
@Micha-Btz : According to my analysis, only three patches were missing, and those three have been pushed into the test branch (as mentioned before). 
The mentioned file **LP_r37-r38_Changes.txt** file contains all _r37 >> _r38 patches - as far as I can say, everything else is already present. 
Since you agree, that we should skip the mentioned telephony patch, we can close this issue, unless you would like to have a look on your end - more people looking at this is always a good idea, in my opinion.

**Comment by MSe1969** [comment]
Closing the issue now - test branch running fine
