### ISSUE TITLE
Scan WiFi networks in LP (cm-12.1)

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#19]
Different from android 6 and above, the list of available WiFi networks can be obtained without having access to the coarse location in our android 5. The "CM Privacy Guard" refers to this as "Location", but the access can be obtained independently and is simply granted by default.

The proposed change is to:
1. Make AppOps (the underlying API of privacy guard) ask for the existing OP_WIFI_SCAN AppOp instead of automatically granting access to it (AppOpsManager.MODE_ASK instead of AppOpsManager.MODE_ALLOWED)
2. Label "Scan WiFi networks" properly

**Comment by MSe1969** [comment]
see frameworks/base in cm-12.1-test

**Comment by Micha-Btz** [comment]
I will test this for now to commit to local manifest

**Comment by MSe1969** [comment]
Oh, thanks for that (just noticed I missed to put frameworks/base into the local manifest, glad you've spotted it)

**Comment by Micha-Btz** [comment]
Build and run fine. But difficult to test. Did you now an app to check if is work correctly?

**Comment by MSe1969** [comment]
I use for example Wi-Fi Privacy Policy (available in F-Droid and Play store) since long time, so my perfect candidate to test :)

**Comment by Micha-Btz** [comment]
Ok, tested with it. Works.

**Comment by MSe1969** [comment]
thanks f. testing - as it is part of the test branch, I'll close the issue
