### ISSUE TITLE
PrivacyGuard / AppOps improvements (backport cm-13.0 and above)

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#21]
Inspired by this (not yet merged) cm-14.1 patch https://review.lineageos.org/#/c/197357/ (note: The patch itself is completely irrelevant for us, as the mentioned AppOps are not defined in cm-12.1), I have checked, which of the defined AppOps are part of an "Ops template" (which is the pre-requisite to see and change them in the privacy guard - as shown in the patch (tested already in cm-13), once an EXISTING Op is added to the template, PrivacyGuard lets you toggle it.

This is the list:
OP_VIBRATE
OP_POST_NOTIFICATION
OP_WRITE_SETTINGS
OP_ACCESS_NOTIFICATIONS
OP_PLAY_AUDIO
OP_READ_CLIPBOARD
OP_WRITE_CLIPBOARD
OP_TAKE_MEDIA_BUTTONS
OP_TAKE_AUDIO_FOCUS
OP_AUDIO*    (misc. volume controls)
OP_GET_USAGE_STATS
OP_MUTE_MICROPHONE
OP_TOAST_WINDOW

As Android 5 does not have runtime permissions (cm-13.0 and above still have those AppOps despite the new runtime permissions: Many apps simply refuse to even launch, if users do not grant the entire bunch of requested permissions, so even with runtime permissions, AppOps is necessary :) ) - so a couple of them should be added to the respective templates according to the coding of cm-13.0 and above.

My point of view would be the following:
**Category A - "Privacy / Tracking / Spying" - those should be added**
OP_ACCESS_NOTIFICATIONS   (DEVICE_TEMPLATE, like in cm-13 and above)
OP_READ_CLIPBOARD   (PERSONAL_TEMPLATE, like in cm-13 and above)
OP_WRITE_CLIPBOARD   (PERSONAL_TEMPLATE, like in cm-13 and above)
OP_GET_USAGE_STATS (cm-14.1 has a change in preparation to show it)

**Category B - "Annoyance" - question of our preference**
cm-13.0 and above have them in the MEDIA_TEMPLATE - well, at least removing the "Vibrate" ability from some apps could become useful :)
OP_VIBRATE
OP_PLAY_AUDIO
OP_TAKE_MEDIA_BUTTONS
OP_TAKE_AUDIO_FOCUS
OP_AUDIO*
OP_MUTE_MICROPHONE

As indicated, change is simple and could be considered a backport from cm-13, as we do not add any new feature, but simple make use of an already existing feature.

I have started with Category A and tested already successfully (see packages/apps/Settings).
Please review, test and advise, whether we should also do Category B.

**Comment by MSe1969** [comment]
UPDATE:
1. OP_GET_USAGE_STATS is linked to the respective permission and this is already a switchable toggle in the Settings app: Security >> Apps with usage access - so not really necessary.
2. Have added OP_VIBRATE to media template, this is simply too useful :)

**Comment by Micha-Btz** [comment]
Adding new possibilities to Privacy Guard is a nice to have but I see here much potential for problems we should test it quite intensive and it should not be mixed with upcoming Feb patches.

**Comment by MSe1969** [comment]
Well... yes and no!

"Privacy Guard" in fact is nothing else but a front-end to an existing API called "AppOps", which was introduced in Android 4.3 (JellyBean). Google later removed the **Settings app frontend** from it (not the API, and CyanogenMod simply preserved the AppOps settings app and started improving it).
AppOps "in official Google language" is a development API. Its default frontend is a command line interface, for which you need an adb shell. (Depending on Android version, the command is either `appops` or `cmd appops`)
Not really widely known, but you can use AppOps via adb even on every unrooted device with stock ROM having Android 4.4 or higher! (AOSP keeps adding Ops in every Android version).

*CM/LineageOS PG consists of three "areas":*
A) AppOps Manager and Service in frameworks/base to define which Ops exist and to host the API itself to assign an Op, to change its status and to get the app status (CM/LineageOS have added some more Ops compared to AOSP, but not too many)
Please note: My patch of this issue does not change anything here!

B) The "logic behind", i.e. the API calls throughout the AOSP core code to change the system behavior in case of an AppOps denial - Yes, *THIS* part, i.e. adding additional code to apply restrictions, is indeed critical and requires thorough testing (CM/LineageOS did so for newly added Ops, but as already mentioned, the vast majority of Ops comes from AOSP itself)
Please note: My patch of this issue does not change anything here

C) The "Settings app frontend"
The code here is based on so-called Ops templates, which are arrays containing the respective OP codes and whether the are linked to a permission. Only AppOp codes being part of a template are subject to be available in the Privacy Guard editor, that's it.
My change is simply to add already EXISTING OP-codes to existing templates to allow editing them. As of now, those codes could only be set through an adb shell or a root shell. If you look at the commit, you'll see. It's easy to reliably test this.

Hence, only modifying the templates in section C can't harm the system, so we CAN make it part of the February ASB release. However - and here I 100% agree with you - adding new OP codes to section A and adding code in core components of Android (like the various frameworks repos) to implement the respective restriction logic indeed is critical...
