### ISSUE TITLE
GApps: Custom-ROM "whitelisting"

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#26]
Please have a look at this article:
https://www.xda-developers.com/google-blocks-gapps-uncertified-devices-custom-rom-whitelist/

We should first of all find out, whether Android 5.1.1 is also affected or not (as - according to a similar article in 'ars technica' - Googles main intention behind is to fight unlicensed importers flashing GApps to Chinese models not licensed)

If we're affected as well, I see two potential impacts on our ROM:

**1. SetupWizard**
Can a user get out of GMS setup or will he/she be 'trapped'? An easy solution could be to simply skip (and bury) the GMS setup.

**2. How to easily get the Android-ID**
Describing how to setup and use 'adb' is maybe not the best way forward just to get the android-id.
Maybe some tap in the settings app (device info page) to copy the ID into the clipboard or similar?

EDIT: The IMEI in fact is needed, according to above (updated) article.
Whether we are affected, would need to be tested by one of you, as I don't use Google at all.
Test would be: Backup in TWRP, factory reset, go through setup process (make sure to be connected via WLAN)

**Comment by MSe1969** [comment]
@hahnjo - you are using Gapps, right? 
Whenever you have time, could you please perform a test (manually flash newest GApps to have them on system partition, twrp backup, factory reset) to see whether the 5.1 GApps also show this behavior? 
If not, let's just close this issue w/o further action - if yes, we need to look whether we need to do something, in case, the user would be "trapped" during Setup... Thanks!

**Comment by hahnjo** [comment]
Yes, I do use them but I don't know when / if I'll find time.

In any case I think the user may just skip adding a Google Account?

**Comment by MSe1969** [comment]
If that is the case, I do not see an issue at all - I would however like to make sure that the user does not end up "trapped" in the SetupWizard - the SetupWizard is a bit nasty sometimes. That's all. As said, if there is 
a. either no such behavior, 
b. or the user can easily skip the Google account setup / logon and normally end the SetupWizard, 
we are fine and can close the issue.

**Comment by MSe1969** [comment]
Did a test with newest GApps and full wipe - issue does **not** occur on 5.1, further, as indicated, user can opt to skip GMS setup -  so no issue at all, closing this one w/o further action
