### ISSUE TITLE
Fix in Apollo player

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#29]
https://review.lineageos.org/#/c/211074/ seems to fix a bug in the Apollo music player. Seems this would apply to our cm-12.1 as well, since there haven't been any commits in cm-12.x

**Comment by Micha-Btz** [comment]
ok. Maybe we can test if we can switch to elven since apollo is not maintained anymore I think.
https://github.com/LineageOS/android_packages_apps_Eleven

**Comment by MSe1969** [comment]
Apollo is still the music player of Omnirom until 7.1, although not being actively maintained, commits mainly translation imports - as it runs stable, there maybe is no need to apply further commits?
On the other hand, Eleven has cm-12.x branches, too - it seems to have been actively maintained already during cm-12.x times! Looking at the commits in cm-13.0, there were mainly adaptations to incorporate the MM permission model and backports of cm-14.x bugfixes. Eleven has as well not really been "maintained" in cm-14.x - Security-wise, a media player is mainly a "frontend" using the media framework being patched every month through ASB. So a stable player would not really need to be maintained, unless new features are applied or obvious bugs to be fixed.
What would be the advantage of switching to Eleven? Does Eleven have any cool feature, which Apollo is badly lacking?

**Comment by MSe1969** [comment]
Since I am back now, I have checked our repo (had only mobile access, when I opened the issue).
In fact, cm-12.1 **uses** already Eleven, and not Apollo (but still with the Apollo icon), so I was on the complete wrong path here - will therefore simply close this issue and sorry for any confusion
