### ISSUE TITLE
Backport https://review.lineageos.org/210741 (Dialer / GDPR)

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#30]
We should backport this change: https://review.lineageos.org/210741
Dialer: comply with EU's GDPR 
Disable lookup by default and add a disclaimer for the feature

**Comment by Micha-Btz** [comment]
agreed

**Comment by MSe1969** [comment]
Forked in our repo, backported patch, adapted and tested successfully
Will be shipped within April ASB, so closing issue

**Comment by MSe1969** [comment]
Issue re-opened - default settings are not "off" when initially (wipe, fresh install) launched

**Comment by Micha-Btz** [comment]
What's the state with this? I don't find any settings related to that in dailer options. Or does it only come up in newly installed roms?

**Comment by MSe1969** [comment]
Lookup settings ("Telefonnummersuche") - supposed to have those settings all disabled by default, when newly installing the ROM, plus a warning/disclaimer. Doesn't work yet, so maybe we should skip for the ASB build for now

**Comment by MSe1969** [comment]
Found the root cause and fixed it:
https://github.com/cm12-amami/android_frameworks_base/commit/54b3e0f542d97f9950a523cf84305ce7b4c1f68d

So closing this issue now
