### ISSUE TITLE
Cloudflare instead of Google DNS as default fallback

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#32]
We should apply this patch:
https://github.com/CopperheadOS/platform_frameworks_base/commit/87258241045b197a00329dcdfe7783567cdf7a35
(Cloudflare DNS has a better privacy policy than Google Public DNS and has DNS-over-TLS and DNS-over-HTTPS)
- Thoughts?

**Comment by Micha-Btz** [comment]
I don't really trust Cloudflare more than Google, but both have the structure to compensate a server fault. Personally I would prefer a server from https://www.kuketz-blog.de/empfehlungsecke/#dns . The problem is, that if we choose one of these servers and the server is not reachable the internall doesn't work at all.

**Comment by MSe1969** [comment]
I 100% agree to your point of view. In fact, my thought is that I view Cloudflare "slightly less bad/evil" compared to Google (in school marks a 4- compared to a 5), that is why I think it is worth to do it... I personally use an AFWall custom script to set my own DNS

**Comment by Micha-Btz** [comment]
I also use an afwall custom script https://github.com/Micha-Btz/freecyngn/blob/master/aafwall.sh#L33
and I have had also problems when the dns server was not reachable. So I think Cloudflare is the way to choose.

**Comment by MSe1969** [comment]
https://github.com/cm12-amami/android_frameworks_base/commit/8bd15de5cb36b782e24b1503d56e3b2c30048897

**Comment by Micha-Btz** [comment]
Let's do this.

**Comment by MSe1969** [comment]
In our test branch, the following is already set, which will finally become part of the May ASB fixes:
- Cloudflare default DNS (this issue)
- Additional fix wrt awl's reported AppOps MODE_ASK issue
- Slight bugfix in Kernel (one previous commit was missing one item)

So closing this issue now.
