### ISSUE TITLE
Settings/DeviceInfo - Patch level explanation and disclaimer

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#40]
In the 'cm11' channel on LineageOS' Slack workspace, a discussion about the shown patch level is ongoing and has led to the linked proposal here:
https://review.lineageos.org/#/c/LineageOS/android_packages_apps_Settings/+/230054/

Should we apply this for our build?

**Comment by Micha-Btz** [comment]
As everyone should know, this is best of effort. So for me it is not necessary  to mention it again, but why not. :-)

**Comment by MSe1969** [comment]
Have updated the test branch, have a look whether you like it or not... (If not, we can get rid of the commits easily)

**Comment by MSe1969** [comment]
merged, so closing this issue
