### ISSUE TITLE
Secure some tiles

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#41]
The following tiles are fully accessible, even if the lock screen with password/PIN protection of the device is active:

- WIFI (on/off toggle)
- Bluetooth (on/off toggle)
- Airplane mode 
- Hotspot (on/off toggle)
- NFC (on/off toggle)

For all of them, it would be better, if access to those tiles would require authentication.
Respective patches to be back-ported can be found as outlined below:

WIFI
https://github.com/AndroidHardeningArchive/platform_frameworks_base/commit/9e56f8ce6a66eea3b2910f7582eadd69283e5f25

Bluetooth
https://github.com/AndroidHardeningArchive/platform_frameworks_base/commit/4e3cf5bdcebf59593b671afc764ef0a2ddddac21

Airplane mode:
https://github.com/AndroidHardeningArchive/platform_frameworks_base/commit/4441e244eae382e7e8f734fc0c26f0bc5eb8b327

Hotspot:
https://github.com/AndroidHardeningArchive/platform_frameworks_base/commit/3c811f19cb47792e56f57052658896ee2ad7ff61

NFC
https://github.com/AndroidHardeningArchive/platform_frameworks_base/commit/1f9fcd6df6158079ef68cf2507cd79bc2d4b2b36

**Comment by Micha-Btz** [comment]
I wouldn't change this behaviour, or at least make it optional. Sure, someone can take your phone and disable wlan, but it makes no disaster. But I can enable bluetooth in my car without unlock the phone.

**Comment by MSe1969** [comment]
At least Hotspot should be protected IMO, if you have it configured, it is simply switched on if you tap on it.
WiFi and BT I tend to agree with your point of view.
Airplane mode is something you don't do frequently, but can be nasty if some "I am soo funny" kid switches your phone whilst you're distracted.

**Comment by MSe1969** [comment]
NFC, I don't use myself, so no opinion. I've listed all patches to secure the tiles.

**Comment by Micha-Btz** [comment]
I don't use NFC too, but maybe we should do it or leave it. Since it can be problematic to explain why some tiles act so and others act different. For my point of view, I would say leave it. But as I remember right the was a question on xda for this. Maybe ask the user?

**Comment by MSe1969** [comment]
Tiles behave differently already today. Some are secured, some are not, some only allow on/off and require authentication only for configuration. 
I am for protection of at least hotspot and airplane mode.

**Comment by Micha-Btz** [comment]
ok, then let's do it.

**Comment by MSe1969** [comment]
different from Higher releases, this is already implemented in cm-12.1, but in a different way (one could even say "more elegantly", but it depends on personal taste):
Settings => Notification Drawer => Hide sensitive tiles when locked

So I will close this issue w/o further action
