### ISSUE TITLE
Additional Spectre v1 kernel mitigations

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#47]
Found some additional spectre v1 mitigations for kernel - will apply to test branch

**Comment by MSe1969** [comment]
Applied: See last 12 commits in 'cm-12.1-test' branch of our kernel, ready to test!

**Comment by Micha-Btz** [comment]
build and run fine. If it works we only can hope I think.

**Comment by MSe1969** [comment]
Thanks for testing!

**Comment by MSe1969** [comment]
Looks also good on my side, merged to stable branch.
Closing the issue
