### ISSUE TITLE
su: apply some older patches from LineageOS 13

### ISSUE THREAD

**Issue by MSe1969** [cm12-amami/discussion#7]
The cm-13.0 branch of LineageOS (CyanogenMod) contains a couple of older improvements / patches. Although the background of the claimed su vuln. is not yet disclosed, some of those patches look meaningful and should also applied in our cm-12.1 branch

**Comment by Micha-Btz** [comment]
The patches you added seems to work well. There are more patches we should add?

**Comment by MSe1969** [comment]
not for su, I think - on my device, it also seems to work well.
Should we merge into the stable branch or wait for the next ASB?

**Comment by Micha-Btz** [comment]
let's wait some days to be sure there are no problems and then ship with asb12/2017
which is also near.

**Comment by MSe1969** [comment]
Okay, merged together with December ASB into stable branch and shipped ROM - so closing this issue
